server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/stc
    username: stc
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: true